-d C:\Users\phuta\Documents\GitHub\EQMAT5\eq-controller\impl\gwsynthesis\eq-controller.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\phuta\Documents\GitHub\EQMAT5\eq-controller\src\eq-controller.cst
-cfg C:\Users\phuta\Documents\GitHub\EQMAT5\eq-controller\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
